// Canonical locality values for new BGM enrollments.
// Source reviewed against Malta's Office of the Address Registrar local-council list.
// Existing historical member town strings are intentionally not rewritten.
export const MALTA_LOCALITIES = [
  "Birkirkara",
  "Birżebbuġa",
  "Bormla",
  "Floriana",
  "Għajnsielem",
  "Ħ'Attard",
  "Ħad-Dingli",
  "Ħal Balzan",
  "Ħal Għargħur",
  "Ħal Għaxaq",
  "Ħal Kirkop",
  "Ħal Lija",
  "Ħal Luqa",
  "Ħal Qormi",
  "Ħal Safi",
  "Ħal Tarxien",
  "Ħaż-Żabbar",
  "Ħaż-Żebbuġ (Malta)",
  "Il-Belt Valletta",
  "Il-Birgu",
  "Il-Fgura",
  "Il-Fontana",
  "Il-Gudja",
  "Il-Gżira",
  "Il-Ħamrun",
  "Il-Kalkara",
  "Il-Marsa",
  "Il-Mellieħa",
  "Il-Mosta",
  "Il-Munxar",
  "Il-Qala",
  "Il-Qrendi",
  "In-Nadur",
  "In-Naxxar",
  "Ir-Rabat (Għawdex)",
  "Ir-Rabat (Malta)",
  "Is-Siġġiewi",
  "Is-Swieqi",
  "Ix-Xagħra",
  "Ix-Xewkija",
  "Ix-Xgħajra",
  "Iż-Żebbuġ (Għawdex)",
  "Iż-Żejtun",
  "Iż-Żurrieq",
  "L-Għarb",
  "L-Għasri",
  "L-Iklin",
  "L-Imdina",
  "L-Imġarr",
  "L-Imqabba",
  "L-Imsida",
  "L-Imtarfa",
  "L-Isla",
  "Marsaskala",
  "Marsaxlokk",
  "Paola",
  "Pembroke",
  "San Ġiljan",
  "San Ġwann",
  "San Lawrenz",
  "San Pawl il-Baħar",
  "Santa Luċija",
  "Santa Venera",
  "Ta' Kerċem",
  "Ta' Sannat",
  "Ta' Xbiex",
  "Tal-Pietà",
  "Tas-Sliema",
] as const;

export type MaltaLocality = (typeof MALTA_LOCALITIES)[number];
